# Generated by Django 5.1 on 2024-08-20 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNueva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='comision',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
