# Generated by Django 5.1 on 2024-08-20 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppNueva', '0002_curso_comision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='comision',
        ),
    ]
