# Generated by Django 5.1 on 2024-08-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNueva', '0003_remove_curso_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
