# Generated by Django 5.1 on 2024-08-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNueva', '0004_alter_curso_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='comision',
            field=models.IntegerField(),
        ),
    ]
