# Generated by Django 5.1 on 2024-08-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNueva', '0007_alter_curso_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
