# Generated by Django 5.1 on 2024-08-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppNueva', '0008_estudiante_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='direccion',
        ),
    ]
