# Generated by Django 5.1 on 2024-08-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNueva', '0011_remove_curso_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
    ]
